/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as MusicIndexRouteImport } from './routes/music';
import { Route as SettingsIndexRouteImport } from './routes/settings';
import { Route as StatisticsIndexRouteImport } from './routes/statistics';
import { Route as TracksIndexRouteImport } from './routes/tracks';
import { Route as PlaylistsIndexRouteImport } from './routes/playlists';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any);

const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any);

const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/statistics/',
  path: '/statistics/',
  getParentRoute: () => rootRouteImport,
} as any);

const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any);

const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/music': typeof MusicIndexRoute;
  '/settings': typeof SettingsIndexRoute;
  '/statistics': typeof StatisticsIndexRoute;
  '/tracks': typeof TracksIndexRoute;
  '/playlists': typeof PlaylistsIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/music': typeof MusicIndexRoute;
  '/settings': typeof SettingsIndexRoute;
  '/statistics': typeof StatisticsIndexRoute;
  '/tracks': typeof TracksIndexRoute;
  '/playlists': typeof PlaylistsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/music/': typeof MusicIndexRoute;
  '/settings/': typeof SettingsIndexRoute;
  '/statistics/': typeof StatisticsIndexRoute;
  '/tracks/': typeof TracksIndexRoute;
  '/playlists/': typeof PlaylistsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/music' | '/settings' | '/statistics' | '/tracks' | '/playlists';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/music' | '/settings' | '/statistics' | '/tracks' | '/playlists';
  id: '__root__' | '/' | '/music/' | '/settings/' | '/statistics/' | '/tracks/' | '/playlists/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MusicIndexRoute: typeof MusicIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  StatisticsIndexRoute: typeof StatisticsIndexRoute;
  TracksIndexRoute: typeof TracksIndexRoute;
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/music/': {
      id: '/music/';
      path: '/music';
      fullPath: '/music';
      preLoaderRoute: typeof MusicIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings/': {
      id: '/settings/';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/statistics/': {
      id: '/statistics/';
      path: '/statistics';
      fullPath: '/statistics';
      preLoaderRoute: typeof StatisticsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/tracks/': {
      id: '/tracks/';
      path: '/tracks';
      fullPath: '/tracks';
      preLoaderRoute: typeof TracksIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/playlists/': {
      id: '/playlists/';
      path: '/playlists';
      fullPath: '/playlists';
      preLoaderRoute: typeof PlaylistsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MusicIndexRoute: MusicIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatisticsIndexRoute: StatisticsIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
